<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vishal Sampath Kumar">

<title>Assignment 4</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/clipboard/clipboard.min.js"></script>
<script src="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/quarto-html/popper.min.js"></script>
<script src="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/quarto-html/anchor.min.js"></script>
<link href="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/quarto-html/quarto-syntax-highlighting-7c69b197886ae2a34062761d21e44731.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Assignment4_VISHAL_SAMPATH_KUMAR_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#data-details" id="toc-data-details" class="nav-link active" data-scroll-target="#data-details"><span class="header-section-number">1</span> Data Details</a></li>
  <li><a href="#blog-post" id="toc-blog-post" class="nav-link" data-scroll-target="#blog-post"><span class="header-section-number">2</span> Blog post</a>
  <ul class="collapse">
  <li><a href="#why-take-a-look-at-parking-congestion-data" id="toc-why-take-a-look-at-parking-congestion-data" class="nav-link" data-scroll-target="#why-take-a-look-at-parking-congestion-data"><span class="header-section-number">2.1</span> Why take a look at parking congestion data?</a></li>
  <li><a href="#data-sources-for-analysing-parking-occupancy-in-melbourne" id="toc-data-sources-for-analysing-parking-occupancy-in-melbourne" class="nav-link" data-scroll-target="#data-sources-for-analysing-parking-occupancy-in-melbourne"><span class="header-section-number">2.2</span> Data Sources for Analysing Parking Occupancy in Melbourne</a></li>
  <li><a href="#what-does-the-data-tell-us" id="toc-what-does-the-data-tell-us" class="nav-link" data-scroll-target="#what-does-the-data-tell-us"><span class="header-section-number">2.3</span> What does the data tell us?</a></li>
  <li><a href="#conclusion--so-what" id="toc-conclusion--so-what" class="nav-link" data-scroll-target="#conclusion--so-what"><span class="header-section-number">2.4</span> Conclusion- So what?</a></li>
  </ul></li>
  <li><a href="#behind-the-scenes" id="toc-behind-the-scenes" class="nav-link" data-scroll-target="#behind-the-scenes"><span class="header-section-number">3</span> Behind the Scenes</a>
  <ul class="collapse">
  <li><a href="#data-processing-that-wasnt-sexy" id="toc-data-processing-that-wasnt-sexy" class="nav-link" data-scroll-target="#data-processing-that-wasnt-sexy"><span class="header-section-number">3.1</span> 1) Data processing that wasn’t “sexy”</a></li>
  <li><a href="#challenges-faced-and-limitations" id="toc-challenges-faced-and-limitations" class="nav-link" data-scroll-target="#challenges-faced-and-limitations"><span class="header-section-number">3.2</span> 2) Challenges faced and limitations</a></li>
  <li><a href="#imperfect-parts-and-future-improvement" id="toc-imperfect-parts-and-future-improvement" class="nav-link" data-scroll-target="#imperfect-parts-and-future-improvement"><span class="header-section-number">3.3</span> 3) Imperfect parts and future improvement</a></li>
  <li><a href="#ai-as-a-supporting-tool" id="toc-ai-as-a-supporting-tool" class="nav-link" data-scroll-target="#ai-as-a-supporting-tool"><span class="header-section-number">3.4</span> 4) AI as a supporting tool</a></li>
  <li><a href="#iterative-process" id="toc-iterative-process" class="nav-link" data-scroll-target="#iterative-process"><span class="header-section-number">3.5</span> 5) Iterative process</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 4</h1>
<p class="subtitle lead">Parking congestion in Melbourne CBD</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Vishal Sampath Kumar </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="data-details" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="data-details"><span class="header-section-number">1</span> Data Details</h2>
<section id="topic-of-this-work" class="level4" data-number="1.0.1">
<h4 data-number="1.0.1" class="anchored" data-anchor-id="topic-of-this-work"><span class="header-section-number">1.0.1</span> Topic of this work</h4>
<p>Which Melbourne parking zones are most consistently congested, and how does that congestion vary by time of day and day of week?</p>
</section>
<section id="why-this-topic" class="level4" data-number="1.0.2">
<h4 data-number="1.0.2" class="anchored" data-anchor-id="why-this-topic"><span class="header-section-number">1.0.2</span> Why this topic</h4>
<p>I chose this topic because I live near the CBD, whenever I have friends coming over or we plan a night out, figuring out parking is always a painpoint and an item of discussion that has caused many plans to fall through before, which is what led me to investigate this topic and shape my research question around parking congestion. This topic is engaging to me because it connects everyday urban movement data with practical questions about how city space is used, which makes the project practical and interesting.</p>
</section>
<section id="data-description" class="level4" data-number="1.0.3">
<h4 data-number="1.0.3" class="anchored" data-anchor-id="data-description"><span class="header-section-number">1.0.3</span> Data description</h4>
<p>I used the datasets described below to analyse recurring parking congestion in Melbourne. Together, these files provide timestamped bay status information and spatial location data, which makes them suitable for both time-based and map-based analysis.</p>
<p><strong>Datasets:</strong></p>
<ol type="1">
<li><p><strong>On-street Parking Bay Sensors</strong></p>
<ul>
<li>Source: City of Melbourne Open Data Portal.</li>
<li>Link: (data.melbourne.vic.gov.au). <a href="https://data.melbourne.vic.gov.au/explore/dataset/on-street-parking-bay-sensors/information/?dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJjb2x1bW4iLCJmdW5jIjoiQ09VTlQiLCJ5QXhpcyI6ImJheV9pZCIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6InJhbmdlLWN1c3RvbSJ9XSwieEF4aXMiOiJsYXN0dXBkYXRlZCIsIm1heHBvaW50cyI6NTAsInNvcnQiOiIiLCJ0aW1lc2NhbGUiOiJkYXkiLCJjb25maWciOnsiZGF0YXNldCI6Im9uLXN0cmVldC1wYXJraW5nLWJheS1zZW5zb3JzIiwib3B0aW9ucyI6e319LCJzZXJpZXNCcmVha2Rvd24iOiJ6b25lX251bWJlciJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZX0%3D">On-street Parking Bay Sensors</a> .</li>
<li>Content: Live parking bay sensor data showing whether a vehicle is present or not present, along with spatial coordinates and kerbside ID.</li>
<li>Data type: Observational administrative open data, effectively a live operational record rather than a sample or experiment.</li>
<li>Update frequency: Approximately every two minutes.</li>
<li>Licence: CC BY / Creative Commons Attribution 4.0.</li>
<li>Limitations: Depends on sensor reliability, may contain missing values, and reflects bay status rather than the full context of driver behaviour.</li>
<li>Privacy/Ethics: Low privacy risk because the data concerns parking bays rather than named individuals, but the analysis will remain aggregated and will not attempt to identify vehicles or people.</li>
</ul></li>
<li><p><strong>On-street Parking Bay Sensors Spatial File (GeoJSON or SHP)</strong></p>
<ul>
<li>Source: Same City of Melbourne dataset page.</li>
<li>Link: (data.melbourne.vic.gov.au). <a href="https://data.melbourne.vic.gov.au/explore/dataset/on-street-parking-bay-sensors/information/?dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJjb2x1bW4iLCJmdW5jIjoiQ09VTlQiLCJ5QXhpcyI6ImJheV9pZCIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6InJhbmdlLWN1c3RvbSJ9XSwieEF4aXMiOiJsYXN0dXBkYXRlZCIsIm1heHBvaW50cyI6NTAsInNvcnQiOiIiLCJ0aW1lc2NhbGUiOiJkYXkiLCJjb25maWciOnsiZGF0YXNldCI6Im9uLXN0cmVldC1wYXJraW5nLWJheS1zZW5zb3JzIiwib3B0aW9ucyI6e319LCJzZXJpZXNCcmVha2Rvd24iOiJ6b25lX251bWJlciJ9XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZX0%3D">On-street Parking Bay Sensors</a> .</li>
<li>Content: Spatial representation of the parking sensor data that can be used for mapping sensor locations.</li>
<li>Data type: Spatial open data.</li>
<li>Licence: CC BY / Creative Commons Attribution 4.0.</li>
<li>Limitations: Spatial points help show location, but they do not on their own explain why some areas are more congested than others.</li>
<li>Privacy/Ethics: Public infrastructure data with low privacy risk.</li>
</ul></li>
<li><p><strong>Municipal Boundary</strong></p>
<ul>
<li>Source: City of Melbourne / Victorian Government Data Directory.</li>
<li>Link: [Municipal boundary](<a href="https://data.melbourne.vic.gov.au/explore/dataset/municipal-boundary/." class="uri">https://data.melbourne.vic.gov.au/explore/dataset/municipal-boundary/.</a></li>
<li>Content: Boundary of the City of Melbourne municipality used as the basemap polygon for the spatial plots.</li>
<li>Data type: Spatial boundary data.</li>
<li>Use in project: Provides a recognisable Melbourne map so the parking points can be plotted on the municipality rather than on blank coordinate axes.</li>
</ul></li>
</ol>
</section>
<section id="data-download" class="level4" data-number="1.0.4">
<h4 data-number="1.0.4" class="anchored" data-anchor-id="data-download"><span class="header-section-number">1.0.4</span> Data download</h4>
<p>The following section describes how the data can be downloaded from its original sources and the initial processing steps used for analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"raw_data"</span>), <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>), <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Downloading Dataset 1</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>url_csv <span class="ot">&lt;-</span> <span class="st">"https://data.melbourne.vic.gov.au/explore/dataset/on-street-parking-bay-sensors/download/?format=csv&amp;timezone=Australia/Melbourne&amp;lang=en"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>destfile_csv <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"raw_data/on-street-parking-bay-sensors.csv"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(url_csv, destfile_csv, <span class="at">mode =</span> <span class="st">"wb"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>parking_sensor_raw <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  destfile_csv,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">delim =</span> <span class="st">";"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If the direct download link changes, the file can be downloaded manually from the dataset page and saved as <code>raw_data/on-street-parking-bay-sensors.csv</code>.</p>
<p><strong>Downloading Dataset 2</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>url_geojson <span class="ot">&lt;-</span> <span class="st">"https://data.melbourne.vic.gov.au/explore/dataset/on-street-parking-bay-sensors/download/?format=geojson&amp;timezone=Australia/Melbourne&amp;lang=en"</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>destfile_geojson <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"raw_data/on-street-parking-bay-sensors.geojson"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(url_geojson, destfile_geojson, <span class="at">mode =</span> <span class="st">"wb"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>parking_sensor_geo <span class="ot">&lt;-</span> <span class="fu">st_read</span>(destfile_geojson, <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If working with the downloaded shapefile instead, all associated files (<code>.shp</code>, <code>.shx</code>, <code>.dbf</code>, <code>.prj</code>, <code>.cpg</code>) should be stored together in the same folder before reading the <code>.shp</code> file.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># If using a shapefile instead of geojson:</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># parking_sensor_geo &lt;- st_read(here::here("raw_data/on-street-parking-bay-sensors/on-street-parking-bay-sensors.shp"))</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Downloading the Melbourne municipal boundary</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>boundary_url <span class="ot">&lt;-</span> <span class="st">"https://data.melbourne.vic.gov.au/api/v2/catalog/datasets/municipal-boundary/exports/geojson"</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>boundary_file <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"raw_data/municipal-boundary.geojson"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(boundary_url, boundary_file, <span class="at">mode =</span> <span class="st">"wb"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>melbourne_boundary <span class="ot">&lt;-</span> <span class="fu">st_read</span>(boundary_file, <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The municipal boundary file provides the polygon boundary of the City of Melbourne municipality and is used as the background map for the parking plots</p>
</section>
<section id="data-cleaning-and-preparation" class="level4" data-number="1.0.5">
<h4 data-number="1.0.5" class="anchored" data-anchor-id="data-cleaning-and-preparation"><span class="header-section-number">1.0.5</span> Data cleaning and preparation</h4>
<p>Before analysing congestion, the raw parking sensor data needs to be converted into a form that is easier to summarise. That includes parsing timestamps properly, extracting useful time-based variables such as hour and day of week, converting latitude and longitude into numeric form, and creating a simple logical indicator that marks whether a bay is occupied.</p>
<p>The main steps used to process the data are listed below.</p>
<ol type="1">
<li>Import the raw CSV sensor data.</li>
<li>Import the geojson or shapefile spatial data.</li>
<li>Clean variable names.</li>
<li>Parse timestamp fields into proper datetime format.</li>
<li>Create derived variables such as hour, weekday, and date.</li>
<li>Recode <code>status_description</code> into an occupied indicator.</li>
<li>Remove or flag missing zone values.</li>
<li>Summarise occupancy by zone, hour, and weekday.</li>
<li>Save the cleaned analysis file separately from the raw data.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>parking_clean <span class="ot">&lt;-</span> parking_sensor_raw <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">lastupdated =</span> <span class="fu">ymd_hms</span>(lastupdated),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">status_timestamp =</span> <span class="fu">ymd_hms</span>(status_timestamp),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">hour =</span> <span class="fu">hour</span>(status_timestamp),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">day_of_week =</span> <span class="fu">wday</span>(status_timestamp, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">week_start =</span> <span class="dv">1</span>),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">date =</span> <span class="fu">as_date</span>(status_timestamp),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">occupied =</span> <span class="fu">case_when</span>(</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_trim</span>(<span class="fu">str_to_lower</span>(status_description)) <span class="sc">==</span> <span class="st">"present"</span> <span class="sc">~</span> <span class="cn">TRUE</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_trim</span>(<span class="fu">str_to_lower</span>(status_description)) <span class="sc">==</span> <span class="st">"unoccupied"</span> <span class="sc">~</span> <span class="cn">FALSE</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(location, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"latitude"</span>, <span class="st">"longitude"</span>), <span class="at">sep =</span> <span class="st">","</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">latitude =</span> <span class="fu">as.numeric</span>(<span class="fu">str_trim</span>(latitude)),</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">longitude =</span> <span class="fu">as.numeric</span>(<span class="fu">str_trim</span>(longitude))</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(zone_number),</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(status_timestamp),</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(hour),</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(day_of_week),</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(latitude),</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(longitude),</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(occupied)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>parking_clean</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,149 × 12
   lastupdated         status_timestamp    zone_number status_description
   &lt;dttm&gt;              &lt;dttm&gt;                    &lt;dbl&gt; &lt;chr&gt;             
 1 2025-01-22 03:44:37 2024-10-11 04:06:49        7539 Unoccupied        
 2 2025-01-22 03:44:37 2024-10-01 23:22:55        7550 Present           
 3 2025-01-22 03:44:37 2024-10-01 22:50:25        7550 Unoccupied        
 4 2025-01-22 03:44:37 2024-10-01 22:48:56        7549 Unoccupied        
 5 2025-01-22 03:44:37 2024-10-01 22:53:36        7549 Unoccupied        
 6 2025-01-22 03:44:37 2024-10-01 22:33:54        7550 Present           
 7 2025-01-22 03:44:37 2024-10-11 02:41:57        7539 Present           
 8 2025-01-10 02:44:36 2024-08-21 04:13:39        7392 Unoccupied        
 9 2024-12-30 00:44:37 2024-08-18 08:23:46        7394 Unoccupied        
10 2025-01-10 02:44:36 2024-08-14 09:22:05        7392 Unoccupied        
# ℹ 3,139 more rows
# ℹ 8 more variables: kerbsideid &lt;dbl&gt;, location &lt;chr&gt;, latitude &lt;dbl&gt;,
#   longitude &lt;dbl&gt;, hour &lt;int&gt;, day_of_week &lt;ord&gt;, date &lt;date&gt;, occupied &lt;lgl&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(parking_clean, here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/parking_processed.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The cleaning step also removes rows with missing values in the key analytical fields. Based on the output shown below, the cleaned dataset contains 3149 rows and 12 columns, which is the dataset used in the later summaries and visualisations</p>
<p>Since spatial summaries are needed, the processed summaries can later be joined to the spatial data. The City of Melbourne states that the live sensor dataset joins to the parking bays dataset by <code>marker_id</code>, and the sensor dataset joins to the parking restrictions dataset by <code>bay_id</code>.</p>
<p>The GeoJSON version of the sensor dataset is especially useful because it already contains the live parking records together with a <code>geometry</code> column. That makes it more suitable for mapping than relying only on split text coordinates.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>parking_sensor_geo_clean <span class="ot">&lt;-</span> parking_sensor_geo <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">lastupdated =</span> <span class="fu">ymd_hms</span>(lastupdated),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">status_timestamp =</span> <span class="fu">ymd_hms</span>(status_timestamp),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">hour =</span> <span class="fu">hour</span>(status_timestamp),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">day_of_week =</span> <span class="fu">wday</span>(status_timestamp, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">week_start =</span> <span class="dv">1</span>),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">date =</span> <span class="fu">as_date</span>(status_timestamp),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">occupied =</span> <span class="fu">case_when</span>(</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_trim</span>(<span class="fu">str_to_lower</span>(status_description)) <span class="sc">==</span> <span class="st">"present"</span> <span class="sc">~</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_trim</span>(<span class="fu">str_to_lower</span>(status_description)) <span class="sc">==</span> <span class="st">"unoccupied"</span> <span class="sc">~</span> <span class="cn">FALSE</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(zone_number),</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(status_timestamp),</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(hour),</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(day_of_week),</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(occupied)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This spatial version of the live sensor data is used in the blog post maps because it allows the point locations to be plotted directly from the geometry column rather than from manually split coordinate fields.</p>
</section>
<section id="inspecting-the-data" class="level4" data-number="1.0.6">
<h4 data-number="1.0.6" class="anchored" data-anchor-id="inspecting-the-data"><span class="header-section-number">1.0.6</span> Inspecting the data</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(parking_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,149
Columns: 12
$ lastupdated        &lt;dttm&gt; 2025-01-22 03:44:37, 2025-01-22 03:44:37, 2025-01-…
$ status_timestamp   &lt;dttm&gt; 2024-10-11 04:06:49, 2024-10-01 23:22:55, 2024-10-…
$ zone_number        &lt;dbl&gt; 7539, 7550, 7550, 7549, 7549, 7550, 7539, 7392, 739…
$ status_description &lt;chr&gt; "Unoccupied", "Present", "Unoccupied", "Unoccupied"…
$ kerbsideid         &lt;dbl&gt; 66222, 66010, 66032, 66063, 66026, 66074, 66237, 93…
$ location           &lt;chr&gt; "-37.81164001991529,144.96061716652716", "-37.80994…
$ latitude           &lt;dbl&gt; -37.81164, -37.80994, -37.81036, -37.81021, -37.810…
$ longitude          &lt;dbl&gt; 144.9606, 144.9664, 144.9649, 144.9656, 144.9653, 1…
$ hour               &lt;int&gt; 4, 23, 22, 22, 22, 22, 2, 4, 8, 9, 2, 20, 2, 23, 3,…
$ day_of_week        &lt;ord&gt; Fri, Tue, Tue, Tue, Tue, Tue, Fri, Wed, Sun, Wed, W…
$ date               &lt;date&gt; 2024-10-11, 2024-10-01, 2024-10-01, 2024-10-01, 20…
$ occupied           &lt;lgl&gt; FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(parking_sensor_geo_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,149
Columns: 11
$ status_timestamp   &lt;dttm&gt; 2024-10-11 15:06:49, 2024-10-02 09:22:55, 2024-10-…
$ zone_number        &lt;int&gt; 7539, 7550, 7550, 7549, 7549, 7550, 7539, 7392, 739…
$ lastupdated        &lt;dttm&gt; 2025-01-22 14:44:37, 2025-01-22 14:44:37, 2025-01-…
$ kerbsideid         &lt;int&gt; 66222, 66010, 66032, 66063, 66026, 66074, 66237, 93…
$ status_description &lt;chr&gt; "Unoccupied", "Present", "Unoccupied", "Unoccupied"…
$ location           &lt;list&gt; &lt;-37.81164, 144.96062&gt;, &lt;-37.80994, 144.96636&gt;, &lt;-…
$ geometry           &lt;POINT [°]&gt; POINT (144.9606 -37.81164), POINT (144.9664 -…
$ hour               &lt;int&gt; 15, 9, 8, 8, 8, 8, 13, 14, 18, 19, 13, 7, 13, 10, 1…
$ day_of_week        &lt;ord&gt; Fri, Wed, Wed, Wed, Wed, Wed, Fri, Wed, Sun, Wed, W…
$ date               &lt;date&gt; 2024-10-11, 2024-10-02, 2024-10-02, 2024-10-02, 20…
$ occupied           &lt;lgl&gt; FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(melbourne_boundary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 10
$ geo_point_2d &lt;chr&gt; "{ \"lon\": 144.9436365307524, \"lat\": -37.8107306254816…
$ mccid_gis    &lt;int&gt; 1
$ maplabel     &lt;chr&gt; NA
$ name         &lt;chr&gt; "City of Melbourne"
$ xorg         &lt;chr&gt; "GIS Team"
$ mccid_str    &lt;chr&gt; NA
$ xsource      &lt;chr&gt; "Mapbase"
$ xdate        &lt;date&gt; 2008-07-01
$ mccid_int    &lt;chr&gt; "0"
$ geometry     &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((144.9404 -3...</code></pre>
</div>
</div>
<p>The cleaned datasets contains 3149 observations and 12 variables in the main CSV file and 3149 observations and 11 in the cleaned GeoJSON dataset, which indicates that the filtering and recoding steps have left a sizeable working dataset for analysis. The preview also shows the key variables needed later, including timestamps, zone identifiers, occupancy labels, and coordinate values</p>
</section>
<section id="creating-the-data-dictionary-file" class="level4" data-number="1.0.7">
<h4 data-number="1.0.7" class="anchored" data-anchor-id="creating-the-data-dictionary-file"><span class="header-section-number">1.0.7</span> Creating the data dictionary file</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>data_dictionary <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable =</span> <span class="fu">c</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"lastupdated"</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"status_timestamp"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zone_number"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"status_description"</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"kerbsideid"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"location"</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"hour"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"day_of_week"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"date"</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"occupied"</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">description =</span> <span class="fu">c</span>(</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Time the record was last updated"</span>,</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Timestamp of the parking sensor reading"</span>,</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Parking zone identifier"</span>,</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Description of whether a car is present or not present"</span>,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Kerbside identifier"</span>,</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Coordinate/location field"</span>,</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Hour extracted from status_timestamp"</span>,</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Weekday extracted from status_timestamp"</span>,</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Calendar date extracted from status_timestamp"</span>,</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Logical occupied/vacant indicator created for analysis"</span></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">role_in_analysis =</span> <span class="fu">c</span>(</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Checks update recency"</span>,</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Main time variable"</span>,</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Main grouping variable"</span>,</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Defines congestion proxy"</span>,</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Optional finer location grouping"</span>,</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Supports mapping"</span>,</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Used for hourly summaries"</span>,</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Used for weekly summaries"</span>,</span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Used for date-based summaries"</span>,</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Main congestion measure"</span></span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a><span class="fu">write.xlsx</span>(data_dictionary, here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/data-dictionary.xlsx"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="files-included-in-submission" class="level4" data-number="1.0.8">
<h4 data-number="1.0.8" class="anchored" data-anchor-id="files-included-in-submission"><span class="header-section-number">1.0.8</span> Files included in submission</h4>
<p>The submission will include:</p>
<ul>
<li>the raw CSV file;</li>
<li>the raw GeoJSON or shapefile;</li>
<li>the Melbourne municipal boundary GeoJSON;</li>
<li>the processed CSV file;</li>
<li>a readme file describing the source and folder structure;</li>
<li>and a data dictionary saved as an <code>.xlsx</code> file.</li>
</ul>
<p>This documentation makes it clear what was downloaded, what was changed, and what was used in the analysis.</p>
<hr>
</section>
</section>
<section id="blog-post" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="blog-post"><span class="header-section-number">2</span> Blog post</h2>
<section id="why-take-a-look-at-parking-congestion-data" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="why-take-a-look-at-parking-congestion-data"><span class="header-section-number">2.1</span> Why take a look at parking congestion data?</h3>
<p>Parking in the Melbourne CBD is a familiar source of frustration. It affects everyday social plans, visitor access, and how long people spend circling for a spot. Because the City of Melbourne publishes live data from thousands of parking sensors, it is possible to move beyond anecdotal complaints and examine actual patterns of parking pressure.</p>
<p>This blog post asks three connected questions:</p>
<ul>
<li><p><strong>Which zones appear most consistently occupied?</strong></p></li>
<li><p><strong>How does occupancy vary by hour?</strong></p></li>
<li><p><strong>Does occupancy also vary across the days of the week?</strong></p></li>
</ul>
<p>The emphasis is on repeated patterns rather than one-off counts, since zones that stay busy across many windows matter more than brief spikes. By combining grouped summaries and maps, the analysis identifies not just where parking is full, but where it appears persistently full over time.</p>
</section>
<section id="data-sources-for-analysing-parking-occupancy-in-melbourne" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="data-sources-for-analysing-parking-occupancy-in-melbourne"><span class="header-section-number">2.2</span> Data Sources for Analysing Parking Occupancy in Melbourne</h3>
<p>Data for visualising parking occupancy in Melbourne is available through the City of Melbourne’s public open data portal. The main dataset used here is the parking sensor dataset, which records whether a bay is occupied or unoccupied at specific timestamps. The spatial file provides the coordinates needed for mapping, and the parking bays file serves as a supporting source for interpretation.</p>
<p>Here, congestion is measured as repeated occupied readings, with “consistent congestion” referring to zones that remain occupied across many hour-by-zone windows. This excludes turnover or duration, an important limitation, but still offers a clear starting point.</p>
</section>
<section id="what-does-the-data-tell-us" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="what-does-the-data-tell-us"><span class="header-section-number">2.3</span> What does the data tell us?</h3>
<p>The City of Melbourne notes that the sensor dataset records whether a vehicle is present or not present and includes spatial coordinate information and kerbside ID. It also states that the data is updated frequently and can be affected by outages or delays, so the <code>lastupdated</code> field is useful for checking freshness.</p>
<p>The first useful summary is the zone-level occupancy table shown below.</p>
<section id="aspect-1-zone-patterns" class="level4" data-number="2.3.1">
<h4 data-number="2.3.1" class="anchored" data-anchor-id="aspect-1-zone-patterns"><span class="header-section-number">2.3.1</span> Aspect 1: Zone patterns</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   zone_number records occ_rate
         &lt;dbl&gt;   &lt;int&gt;    &lt;dbl&gt;
 1        7638      17        1
 2        7614      15        1
 3        7910      14        1
 4        7514      11        1
 5        7220      10        1
 6        7636       9        1
 7        7195       8        1
 8        7089       7        1
 9        7243       7        1
10        7252       7        1</code></pre>
</div>
</div>
<p>The top ten zones all have an occupancy rate of 1. This means every recorded observation for those zones in the cleaned sample was classified as occupied. Among these, zone <strong>7716</strong> stands out with <strong>25 records</strong>. Other highly occupied zones also show complete occupancy but with fewer observations.</p>
<p>This result suggests that some zones were effectively always full during the observed sample but the <code>records</code> column also matters since a zone with identical occupancy across many observations is stronger evidence of persistent congestion than one based on only a handful of rows.</p>
<p>In general though, all these zones have relatively small record counts, which means their perfect occupancy rates, although an informative result, should be interpreted with some caution. It suggests that <strong>some zones in the dataset are consistently busy and may represent areas of especially high parking pressure</strong>.</p>
<p>However, a high mean occupancy on its own does not distinguish between zones that are always busy and zones that only appear in a limited subset of time periods. A second summary considers persistence across hourly windows rather than just the overall average.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   zone_number persist_share
         &lt;dbl&gt;         &lt;dbl&gt;
 1        7002             1
 2        7015             1
 3        7019             1
 4        7089             1
 5        7096             1
 6        7182             1
 7        7185             1
 8        7189             1
 9        7191             1
10        7195             1</code></pre>
</div>
</div>
<p>The persistence table shows that the top ten zones all have a <code>persist_share</code> of 1. This means these zones were above the median hourly occupancy threshold in every observed hourly period used in the calculation.</p>
<p>This is important because it shows that some zones are not merely busy on average, but repeatedly busy across time. The overlap between this persistence table and the earlier occupancy ranking, like zone <strong>7089</strong>, suggests that a smaller subset of zones experiences more durable congestion than the rest of the network.</p>
<p>These summaries make it possible to distinguish between zones that are always busy and zones that are only occasionally busy.</p>
</section>
<section id="aspect-2-how-does-occupancy-change-through-the-day" class="level4" data-number="2.3.2">
<h4 data-number="2.3.2" class="anchored" data-anchor-id="aspect-2-how-does-occupancy-change-through-the-day"><span class="header-section-number">2.3.2</span> Aspect 2: How does occupancy change through the day?</h4>
<p>The hourly summary shows when parking demand is strongest across the day. This helps answer whether congestion is tied to business hours, evening activity, or a broader all-day pattern.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 2
    hour occ_rate
   &lt;int&gt;    &lt;dbl&gt;
 1     0    0.703
 2     1    0.581
 3     2    0.598
 4     3    0.605
 5     4    0.642
 6     5    0.667
 7     6    0.571
 8     7    0.440
 9     8    0.5  
10     9    0.410
# ℹ 14 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment4_VISHAL_SAMPATH_KUMAR_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The hourly pattern is clearly uneven. <strong>Occupancy peaks around midnight, overnight, and in the early hours of the morning</strong>, with <strong>3 AM</strong> reaching roughly <strong>0.77</strong>, which suggests that busy periods are <strong>not limited to standard business hours</strong>. It remains moderate through the early morning, then gradually declines through the late morning and early afternoon.</p>
<p><strong>The lowest point appears around hour 13</strong>, where the occupancy rate falls to about <strong>0.15</strong>. After that, <strong>occupancy begins to rise again through the late afternoon and</strong> <strong>remaining elevated into the evening</strong>.</p>
<p>This suggests that, in this sample, <strong>the most difficult time to find parking is likely to be late afternoon and evening</strong> rather than the middle of the day. That is a useful finding because it suggests the pressure on parking may be linked not only to daytime work activity, but also to later city activity.</p>
</section>
<section id="aspect-3-how-does-occupancy-change-by-day-of-week" class="level4" data-number="2.3.3">
<h4 data-number="2.3.3" class="anchored" data-anchor-id="aspect-3-how-does-occupancy-change-by-day-of-week"><span class="header-section-number">2.3.3</span> Aspect 3: How does occupancy change by day of week</h4>
<p>The next step is to check whether occupancy patterns also differ by weekday. Weekday patterns help distinguish work-related parking demand from weekend or leisure-related demand. If the busiest days differ from the busiest hours, that suggests parking congestion is shaped by more than one urban activity pattern.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  day_of_week occ_rate
  &lt;ord&gt;          &lt;dbl&gt;
1 Mon            0.585
2 Tue            0.543
3 Wed            0.586
4 Thu            0.503
5 Fri            0.468
6 Sat            0.455
7 Sun            0.617</code></pre>
</div>
</div>
<p>The weekday summary shows a clear difference between weekdays and weekends. <strong>Monday has the highest observed occupancy rate at about 0.585</strong>, while <strong>Friday is the lowest at about 0.468</strong> and Sunday remains below 0.4</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment4_VISHAL_SAMPATH_KUMAR_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bar chart reinforces that result visually. <strong>Weekday occupancy is consistently higher than weekend occupancy</strong>, with the sharpest drop occurring on Saturday, and only a slight recovery on Sunday. <strong>Thursday is also somewhat lower than the other weekdays</strong>, but still noticeably above the weekend values.</p>
<p>This suggests that the <strong>strongest parking pressure in the sample is associated more with weekday urban activity</strong> than with weekend demand. In other words, the busiest days are not evenly spread across the week.</p>
</section>
<section id="aspect-4-spatial-pattern" class="level4" data-number="2.3.4">
<h4 data-number="2.3.4" class="anchored" data-anchor-id="aspect-4-spatial-pattern"><span class="header-section-number">2.3.4</span> Aspect 4: Spatial pattern</h4>
<p>Finally, it is useful to plot the locations of the parking observations on a Melbourne map. The spatial view is important because it shows where the persistent congestion is located, not just when it happens. This directly supports the original question by linking repeated occupancy to place, not only time.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment4_VISHAL_SAMPATH_KUMAR_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This map places the parking sensor observations on the municipal boundary of the City of Melbourne and while it does not by itself prove which zones are the most persistently congested, it does provide useful context about where occupied and unoccupied observations are concentrated within the municipality. The spatial plot shows that the sensor points are clustered within a fairly concentrated part of the Melbourne municipal boundary, rather than being evenly spread across the entire map. The red points, which indicate <strong>occupied observations, clearly outnumber the grey unoccupied points in the central cluster</strong>, visually matching the earlier summaries showing occupancy rates above 0.5 for many periods.</p>
</section>
<section id="aspect-5-zone-occupancy-map" class="level4" data-number="2.3.5">
<h4 data-number="2.3.5" class="anchored" data-anchor-id="aspect-5-zone-occupancy-map"><span class="header-section-number">2.3.5</span> Aspect 5: Zone occupancy map</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment4_VISHAL_SAMPATH_KUMAR_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This second map is more directly tied to the research question because it shows the average occupancy rate by location rather than a single raw occupied or unoccupied state. That makes it easier to spot zones that appear persistently busy rather than temporarily full.</p>
</section>
</section>
<section id="conclusion--so-what" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="conclusion--so-what"><span class="header-section-number">2.4</span> Conclusion- So what?</h3>
<p>Going down the rabbit hole of understanding the seemingly inexplicable parking behavior in Melbourne turned a familiar local frustration into a structured data analysis using City of Melbourne parking data.</p>
<p>Overall, the analysis suggests that parking congestion in this sample is both spatially concentrated and strongly time-dependent. Several zones have an occupancy rate of 1.00, and several others also have a persistence score of 1.00, meaning that <strong>repeated congestion is not confined to a single isolated case</strong>.</p>
<p>The time-of-day pattern is especially striking. Occupancy dips in the middle of the day and then rises into the evening and early morning, peaking around 3:00. That means <strong>the most intense parking pressure in this sample does not occur at midday, but at night</strong>.</p>
<p>The weekday pattern is also clear. Monday has the highest occupancy, while Saturday has the lowest, and weekends overall are noticeably less occupied than weekdays. Together, these results suggest that <strong>recurring parking pressure in this dataset is more closely associated with weekday city activity and evening demand than with weekend peaks</strong>.</p>
<p>The first map helps show where these observations are happening. Rather than being evenly spread across the full municipal boundary, the points are clustered in a more central part of Melbourne, and occupied points are visually common within that cluster. This supports the idea that the <strong>occupancy patterns seen in the summaries are tied to a concentrated (CBD and central-eastern) part of the city rather than being uniformly distributed everywhere</strong>.</p>
<p>The second map makes the spatial interpretation clearer by aggregating occupancy at the zone level. Zones with higher occupancy rates stand out in brighter colours, while point size shows that some of these zones are supported by more observations than others. This is important because it adds a second layer of evidence: <strong>not only do some zones look busy in the tables, but those same high-occupancy zones also appear as spatially identifiable parts of the map</strong>.</p>
<p>In summary, the tables, charts, and maps all point in the same direction. <strong>Parking congestion in this sample does not appear to be evenly spread across all zones or all times</strong>. Instead, <strong>it is concentrated in central zones, stronger on weekdays, and especially high in the evening</strong>.</p>
</section>
</section>
<section id="behind-the-scenes" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="behind-the-scenes"><span class="header-section-number">3</span> Behind the Scenes</h2>
<section id="data-processing-that-wasnt-sexy" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data-processing-that-wasnt-sexy"><span class="header-section-number">3.1</span> 1) Data processing that wasn’t “sexy”</h3>
<p>A large part of this project involved unglamorous data processing work that would not usually make it into the blog post itself. The biggest piece of drudgery was getting the raw files into a usable format, especially because the CSVs were separated by semicolons rather than commas, which caused the data to load incorrectly at first. I also had to clean variable names, convert timestamps into datetime objects, create new variables like hour, weekday, and date, and check for missing or inconsistent values before any real analysis could begin. Another repetitive task was working out which dataset should be used for which part of the analysis, because some files overlapped in purpose. While these steps were tedious, they were also important because they made the later summaries and visualisations much easier to produce and trust.</p>
</section>
<section id="challenges-faced-and-limitations" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="challenges-faced-and-limitations"><span class="header-section-number">3.2</span> 2) Challenges faced and limitations</h3>
<p>One of the biggest challenges was deciding how to structure the analysis once I realised that the datasets were not equally useful. At first, I expected to rely on all of them, but after inspection I had to narrow the scope and focus on the live sensor data and its GeoJSON version because they were more current and more directly useful than the parking bays dataset. I also ran into coding issues when working with the spatial data, especially around how to map point geometry properly and how to combine spatial and non-spatial summaries without introducing errors. Another challenge was defining “consistent congestion” in a way that was meaningful rather than just picking the busiest zones by average occupancy. I am most proud of solving the workflow problem by separating the tabular summaries from the spatial analysis, which made the final structure clearer and more defensible.</p>
<p>Here, I was only able to scratch the surface, but in the future I’d like to analyse:</p>
<ul>
<li><p>whether the same zones remain highly occupied across a longer range of dates rather than only within the current sample</p></li>
<li><p>whether weekday and weekend parking patterns differ more sharply when separated by zone</p></li>
<li><p>whether nearby restaurants, offices, events, or other land uses help explain persistent congestion</p></li>
<li><p>and whether a more formal congestion score could be developed by combining occupancy, persistence, and sample size into one measure.</p></li>
</ul>
</section>
<section id="imperfect-parts-and-future-improvement" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="imperfect-parts-and-future-improvement"><span class="header-section-number">3.3</span> 3) Imperfect parts and future improvement</h3>
<p>There are still some imperfect parts of this analysis that I would improve if I had more time. The biggest limitation is that the occupancy measure is based on available sensor readings rather than true parking duration, turnover, or driver behaviour, so it gives a useful but incomplete picture of congestion. Some zones also have small numbers of observations, which means a perfect occupancy rate does not always mean the zone is consistently full across a large sample. Another limitation is that the spatial analysis is still fairly simple, because it shows where congestion appears but does not explain why those zones are busier than others. In future, I would like to extend the time range, compare zones more systematically, and bring in other context such as nearby land use, events, or business activity to better explain the patterns.</p>
</section>
<section id="ai-as-a-supporting-tool" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="ai-as-a-supporting-tool"><span class="header-section-number">3.4</span> 4) AI as a supporting tool</h3>
<p>I used AI as a support tool rather than as a replacement for my own judgement. One useful part of using AI was that it helped me realise that the CSV and GeoJSON files had different strengths and work through through how to simplify my workflow, so I could separate the tabular summaries from the spatial mapping instead of forcing everything into one pipeline. It was a great asset in that regard because it improved both the structure of the analysis and my understanding of how to work with different data formats more effectively. It was also quite useful when I was trying to decide which datasets were actually worth using, because it helped me think through the difference between a dataset that was available and one that was genuinely useful for the question.</p>
<p>AI was not always reliable on its own though, so I had to check and refine a lot of its suggestions. For example, I verified dataset details, checked whether the spatial file actually contained geometry, and corrected the example codes it would give me to fit my dataset and research question, and further iterate and refine it myself to get the outputs I desired. I also questioned some of the analysis suggestions when they looked too complicated or when they duplicated information unnecessarily. In those cases, I used AI more like a brainstorming partner than an authority, and I made sure the final choices still made sense for the assignment.</p>
</section>
<section id="iterative-process" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="iterative-process"><span class="header-section-number">3.5</span> 5) Iterative process</h3>
<p><strong>V1 Reflection:</strong></p>
<p>In this early version, I focused only on getting the data loaded into R. Instead of manually downloading the dtasets from the City of Melbourne website as I did on the submission for early feedback, and then loading them into R, this time I tried to download data directly from the url on Rstudio. However, this time, I noticed that when I download the datasets from the url using R markdown, the downloaded CSV files used a semicolon delimiter, so the dataset loaded as a single column. This is something I will have to fix before proceeding with any further analysis, so at this stage, the main focus is simply getting the file structure and dataset loading working.</p>
<p><strong>V2 Reflection:</strong></p>
<p>In this version, after realizing the delimiter problem, I fixed the import issue from the first draft using <code>read_delim(..., delim = ";")</code> and successfully imported the data into a format that could actually be analysed instead of being read as one long column. I then began cleaning the key variables so the timestamps, zone numbers, and occupancy values could be used properly and also started creating the time-based fields like hour and day of week.</p>
<p>Another thing I learned at this stage was that the location field needed extra wrangling before it could be used in maps. Splitting coordinates into latitude and longitude and checking for missing values took a bit of trial and error, but it was necessary before I could move on to any spatial visualisation. This version still feels very preliminary, but is a major step forward because the dataset is now structured enough to support summaries by time and place and I’ve also added a data dictionary file to supplement understanding.</p>
<p><strong>V3 Reflection:</strong></p>
<p>In this version, I moved beyond just cleaning the data and started building the actual analysis, commentating it along the way with my blog post. The biggest change from the earlier version was that I could now summarise occupancy by zone and time, which meant I was finally able to answer the research question in a more direct way. Additionally, I added more details about the sources and file structure in the README file and also decided to add a spatial aspect to my project by incorporating the municipal boundary and plotting the parking observations on a map, but haven’t implemented it yet.</p>
<p>This stage also showed me that I needed a clearer way of defining “consistent congestion,” because just looking at the busiest zones was not enough. That led me to start thinking more carefully about persistence across time, rather than only average occupancy. At this point, the project is still missing some refinement, but it has already become much stronger because the analysis now combined time-based summaries, which gave me a better sense of what the final report would look like.</p>
<p><strong>V4 Reflection:</strong></p>
<p>In this version, I moved to a more complete analysis that used both the tabular sensor data and the spatial sensor file in a more intentional way and went a step further to interpret and communicate my findings as succinctly as I can. The biggest change from V3 was that I realized that rather than treating spatial data as an afterthought and trying to parse and derive it from the CSV data, instead using the spacial data from GeoJSON directly in the mapping sections while the CSV stayed the main source for zone-level summaries and time-based patterns felt a lot more intuitive and would probably make for a more reliable frame for analysis.</p>
<p>Another important change was that I became more selective about which supporting datasets were actually worth including. After checking the parking bays dataset more carefully, I decided it was not the best fit for the final analysis because it only extended to 2024, which made it older than the live sensor datasets that reached 2026, and it also did not add much beyond what the spatial sensor file already provided. That helped narrow the project to the datasets that were most current and most useful for answering the question.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>